Data_Preparation:
  test_size: 0.2
  random_state: 42

Train:
  Random_Forest:
    n_estimators: 138
    criterion: "squared_error"
    max_depth: 28
    max_features: 1
    min_samples_split: 9
    min_samples_leaf: 6
    max_samples: 0.9732465926878385
    verbose: 1
    n_jobs: 4

  LightGBM:
    n_estimators: 74
    max_depth: 9
    learning_rate: 0.586415155400763
    subsample: 0.9019313990739353
    min_child_weight: 20
    min_split_gain: 0.013654097110983532
    reg_lambda: 97.64570304778138
    n_jobs: 4

